### ISSUE TITLE
PyPDF2.errors.EmptyFileError: Cannot read an empty file

### ISSUE THREAD

**Issue by zwy923** [talkingwallace/ChatGPT-Paper-Reader#7]
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Anaconda3\lib\site-packages\gradio\blocks.py", line 1069, in process_api
    result = await self.call_function(
  File "D:\Anaconda3\lib\site-packages\gradio\blocks.py", line 878, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Anaconda3\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,  File "D:\Anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "D:\Anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "c:\Users\Administrator\Desktop\Paper-Reader\gui.py", line 14, in analyse
    return self.session.read_pdf_and_summarize(pdf_file)
  File "c:\Users\Administrator\Desktop\Paper-Reader\gpt_reader\pdf_reader.py", line 100, in read_pdf_and_summarize
    pdf_reader = PdfReader(pdf_path)
  File "D:\Anaconda3\lib\site-packages\PyPDF2\_reader.py", line 319, in __init__
    self.read(stream)
  File "D:\Anaconda3\lib\site-packages\PyPDF2\_reader.py", line 1414, in read
    self._basic_validation(stream)
  File "D:\Anaconda3\lib\site-packages\PyPDF2\_reader.py", line 1455, in _basic_validation     
    raise EmptyFileError("Cannot read an empty file")

**Comment by ssoro** [comment]
same problem om mac.  Cannot read an empty file!

**Comment by Alpaca4610** [comment]
https://github.com/talkingwallace/ChatGPT-Paper-Reader/issues/3

**Comment by woshiniqiangdadebaba** [comment]
同上

**Comment by Bearbear006** [comment]
same

**Comment by nvknow** [comment]
same
